### ISSUE TITLE
Write unit tests for utils

### ISSUE THREAD

**Issue by liaujianjie** [liaujianjie/react-image-snipper#8]
Utils in https://github.com/liaujianjie/react-image-snipper/tree/master/src/utils need to be tested. It should be relatively straightforward.

**Comment by Kaivosukeltaja** [comment]
I can help with this one.

**Comment by natealcedo** [comment]
Hi @Kaivosukeltaja ! Thanks for taking interest in our side project. For testing, each file should have its own test file. For example, `Action.js` should have a corresponding `Action.spec.js`. Write tests for the main exports of the file in question. Just shoot if you have any questions!

**Comment by Kaivosukeltaja** [comment]
Hi and thanks! A couple of questions: `Action.js` doesn't contain any functions, how should it be tested? Also there's quite a lot going on in `getNewRect()` - could you give a couple of example calls what it does?
